/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MagicIframeEvent,
} from './components/magic-iframe/magic-iframe-event.interface';

export namespace Components {
  interface SebMagicIframe {
    'autoResize': boolean;
    'debug': boolean;
    'height': string;
    'matchContentWidth': boolean | 'auto';
    'minWidth': string;
    'resizeDebounce': number;
    'sanitizeSource': boolean;
    'scaleContent': boolean;
    'scaleDebounce': number;
    /**
    * Properties
    */
    'source': string;
    'styleUrls': Array<string>;
    'styles': string;
  }
}

declare global {


  interface HTMLSebMagicIframeElement extends Components.SebMagicIframe, HTMLStencilElement {}
  var HTMLSebMagicIframeElement: {
    prototype: HTMLSebMagicIframeElement;
    new (): HTMLSebMagicIframeElement;
  };
  interface HTMLElementTagNameMap {
    'seb-magic-iframe': HTMLSebMagicIframeElement;
  }
}

declare namespace LocalJSX {
  interface SebMagicIframe {
    'autoResize'?: boolean;
    'debug'?: boolean;
    'height'?: string;
    'matchContentWidth'?: boolean | 'auto';
    'minWidth'?: string;
    'onMagicIframeEvent'?: (event: CustomEvent<MagicIframeEvent>) => void;
    'resizeDebounce'?: number;
    'sanitizeSource'?: boolean;
    'scaleContent'?: boolean;
    'scaleDebounce'?: number;
    /**
    * Properties
    */
    'source'?: string;
    'styleUrls'?: Array<string>;
    'styles'?: string;
  }

  interface IntrinsicElements {
    'seb-magic-iframe': SebMagicIframe;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'seb-magic-iframe': LocalJSX.SebMagicIframe & JSXBase.HTMLAttributes<HTMLSebMagicIframeElement>;
    }
  }
}


